version: "3"

vars:
  BIN_DIR: bin
  TESTS_DIR: tests
  CLI_DIR: cmd/twinpick-cli
  API_DIR: cmd/twinpick-api
  MCP_DIR: cmd/twinpick-mcp
  GRPC_DIR: cmd/twinpick-grpc
  PROTO_DIR: api/proto

tasks:
  proto:
    desc: "Generate Go code from protobuf files"
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative {{.PROTO_DIR}}/twinpick.proto

  build:api:
    desc: "Build Twinpick API server"
    cmds:
      - go build -o {{.BIN_DIR}}/twinpick-api {{.API_DIR}}/main.go

  build:mcp:
    desc: "Build Twinpick MCP server"
    cmds:
      - go build -o {{.BIN_DIR}}/twinpick-mcp {{.MCP_DIR}}/main.go

  build:cli:
    desc: "Build Twinpick CLI"
    cmds:
      - go build -o {{.BIN_DIR}}/twinpick-cli {{.CLI_DIR}}/main.go

  build:grpc:
    desc: "Build Twinpick gRPC server"
    cmds:
      - go build -o {{.BIN_DIR}}/twinpick-grpc {{.GRPC_DIR}}/main.go

  build:all:
    desc: "Build all Twinpick components"
    deps:
      - build:api
      - build:mcp
      - build:cli
      - build:grpc

  run:api:
    desc: "Start Twinpick API server"
    deps:
      - build:api
    cmds:
      - ./{{.BIN_DIR}}/twinpick-api

  run:mcp:
    desc: "Start Twinpick MCP server"
    deps:
      - build:mcp
    cmds:
      - ./{{.BIN_DIR}}/twinpick-mcp

  run:cli:
    desc: "Run Twinpick CLI"
    deps:
      - build:cli
    cmds:
      - ./{{.BIN_DIR}}/twinpick-cli {{.CLI_ARGS}}

  run:grpc:
    desc: "Start Twinpick gRPC server"
    deps:
      - build:grpc
    cmds:
      - ./{{.BIN_DIR}}/twinpick-grpc

  run:all:
    desc: "Start all Twinpick components"
    deps:
      - build:all
    cmds:
      - task run:api &
      - task run:mcp

  test:api:
    desc: "Run tests for Twinpick API server"
    cmds:
      - ./{{.TESTS_DIR}}/api_test.sh

  test:mcp:
    desc: "Run tests for Twinpick MCP server"
    cmds:
      - ./{{.TESTS_DIR}}/mcp_test.sh

  default:
    desc: "Start Twinpick API server in development mode"
    cmds:
      - task: run:api

  test:
    desc: "Run all tests"
    cmds:
      - go test -v ./...

  test:coverage:
    desc: "Run tests with coverage report"
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -func=coverage.out
      - rm coverage.out
