version: "3"

vars:
  BIN_DIR: bin
  TESTS_DIR: tests
  CLI_DIR: cmd/twinpick-cli
  API_DIR: cmd/twinpick-api
  MCP_DIR: cmd/twinpick-mcp

tasks:
  build:api:
    desc: "Build Twinpick API server"
    cmds:
      - go build -o {{.BIN_DIR}}/twinpick-api {{.API_DIR}}/main.go

  build:mcp:
    desc: "Build Twinpick MCP server"
    cmds:
      - go build -o {{.BIN_DIR}}/twinpick-mcp {{.MCP_DIR}}/main.go

  build:cli:
    desc: "Build Twinpick CLI"
    cmds:
      - go build -o {{.BIN_DIR}}/twinpick-cli {{.CLI_DIR}}/main.go

  build:all:
    desc: "Build all Twinpick components"
    deps:
      - build:api
      - build:mcp
      - build:cli

  run:api:
    desc: "Start Twinpick API server"
    deps:
      - build:api
    cmds:
      - ./{{.BIN_DIR}}/twinpick-api

  run:mcp:
    desc: "Start Twinpick MCP server"
    deps:
      - build:mcp
    cmds:
      - ./{{.BIN_DIR}}/twinpick-mcp

  run:cli:
    desc: "Run Twinpick CLI"
    deps:
      - build:cli
    cmds:
      - ./{{.BIN_DIR}}/twinpick-cli {{.CLI_ARGS}}

  run:all:
    desc: "Start all Twinpick components"
    deps:
      - build:all
    cmds:
      - task run:api &
      - task run:mcp

  test:api:
    desc: "Run tests for Twinpick API server"
    cmds:
      - ./{{.TESTS_DIR}}/api_test.sh

  test:mcp:
    desc: "Run tests for Twinpick MCP server"
    cmds:
      - ./TESTS_DIR/mcp_test.sh

  default:
    desc: "Start Twinpick API server in development mode"
    cmds:
      - task: run:api

  test:
    desc: "Run all tests"
    cmds:
      - go test -v ./...

  test:coverage:
    desc: "Run tests with coverage report"
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -func=coverage.out
      - rm coverage.out
