// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: api/proto/twinpick.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TwinPickService_Pick_FullMethodName       = "/twinpick.TwinPickService/Pick"
	TwinPickService_Spot_FullMethodName       = "/twinpick.TwinPickService/Spot"
	TwinPickService_PickStream_FullMethodName = "/twinpick.TwinPickService/PickStream"
	TwinPickService_SpotStream_FullMethodName = "/twinpick.TwinPickService/SpotStream"
)

// TwinPickServiceClient is the client API for TwinPickService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TwinPickService expose les fonctionnalités de découverte de films
type TwinPickServiceClient interface {
	// Pick retourne les films en commun entre plusieurs watchlists Letterboxd
	Pick(ctx context.Context, in *PickRequest, opts ...grpc.CallOption) (*PickResponse, error)
	// Spot retourne des suggestions de films populaires
	Spot(ctx context.Context, in *SpotRequest, opts ...grpc.CallOption) (*SpotResponse, error)
	// PickStream retourne les films en streaming (un par un)
	PickStream(ctx context.Context, in *PickRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Film], error)
	// SpotStream retourne les suggestions en streaming
	SpotStream(ctx context.Context, in *SpotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Film], error)
}

type twinPickServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTwinPickServiceClient(cc grpc.ClientConnInterface) TwinPickServiceClient {
	return &twinPickServiceClient{cc}
}

func (c *twinPickServiceClient) Pick(ctx context.Context, in *PickRequest, opts ...grpc.CallOption) (*PickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PickResponse)
	err := c.cc.Invoke(ctx, TwinPickService_Pick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinPickServiceClient) Spot(ctx context.Context, in *SpotRequest, opts ...grpc.CallOption) (*SpotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpotResponse)
	err := c.cc.Invoke(ctx, TwinPickService_Spot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinPickServiceClient) PickStream(ctx context.Context, in *PickRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Film], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TwinPickService_ServiceDesc.Streams[0], TwinPickService_PickStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PickRequest, Film]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TwinPickService_PickStreamClient = grpc.ServerStreamingClient[Film]

func (c *twinPickServiceClient) SpotStream(ctx context.Context, in *SpotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Film], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TwinPickService_ServiceDesc.Streams[1], TwinPickService_SpotStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SpotRequest, Film]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TwinPickService_SpotStreamClient = grpc.ServerStreamingClient[Film]

// TwinPickServiceServer is the server API for TwinPickService service.
// All implementations must embed UnimplementedTwinPickServiceServer
// for forward compatibility.
//
// TwinPickService expose les fonctionnalités de découverte de films
type TwinPickServiceServer interface {
	// Pick retourne les films en commun entre plusieurs watchlists Letterboxd
	Pick(context.Context, *PickRequest) (*PickResponse, error)
	// Spot retourne des suggestions de films populaires
	Spot(context.Context, *SpotRequest) (*SpotResponse, error)
	// PickStream retourne les films en streaming (un par un)
	PickStream(*PickRequest, grpc.ServerStreamingServer[Film]) error
	// SpotStream retourne les suggestions en streaming
	SpotStream(*SpotRequest, grpc.ServerStreamingServer[Film]) error
	mustEmbedUnimplementedTwinPickServiceServer()
}

// UnimplementedTwinPickServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTwinPickServiceServer struct{}

func (UnimplementedTwinPickServiceServer) Pick(context.Context, *PickRequest) (*PickResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pick not implemented")
}
func (UnimplementedTwinPickServiceServer) Spot(context.Context, *SpotRequest) (*SpotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Spot not implemented")
}
func (UnimplementedTwinPickServiceServer) PickStream(*PickRequest, grpc.ServerStreamingServer[Film]) error {
	return status.Error(codes.Unimplemented, "method PickStream not implemented")
}
func (UnimplementedTwinPickServiceServer) SpotStream(*SpotRequest, grpc.ServerStreamingServer[Film]) error {
	return status.Error(codes.Unimplemented, "method SpotStream not implemented")
}
func (UnimplementedTwinPickServiceServer) mustEmbedUnimplementedTwinPickServiceServer() {}
func (UnimplementedTwinPickServiceServer) testEmbeddedByValue()                         {}

// UnsafeTwinPickServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TwinPickServiceServer will
// result in compilation errors.
type UnsafeTwinPickServiceServer interface {
	mustEmbedUnimplementedTwinPickServiceServer()
}

func RegisterTwinPickServiceServer(s grpc.ServiceRegistrar, srv TwinPickServiceServer) {
	// If the following call panics, it indicates UnimplementedTwinPickServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TwinPickService_ServiceDesc, srv)
}

func _TwinPickService_Pick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinPickServiceServer).Pick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwinPickService_Pick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinPickServiceServer).Pick(ctx, req.(*PickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinPickService_Spot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinPickServiceServer).Spot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwinPickService_Spot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinPickServiceServer).Spot(ctx, req.(*SpotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinPickService_PickStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PickRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TwinPickServiceServer).PickStream(m, &grpc.GenericServerStream[PickRequest, Film]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TwinPickService_PickStreamServer = grpc.ServerStreamingServer[Film]

func _TwinPickService_SpotStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SpotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TwinPickServiceServer).SpotStream(m, &grpc.GenericServerStream[SpotRequest, Film]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TwinPickService_SpotStreamServer = grpc.ServerStreamingServer[Film]

// TwinPickService_ServiceDesc is the grpc.ServiceDesc for TwinPickService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TwinPickService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "twinpick.TwinPickService",
	HandlerType: (*TwinPickServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pick",
			Handler:    _TwinPickService_Pick_Handler,
		},
		{
			MethodName: "Spot",
			Handler:    _TwinPickService_Spot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PickStream",
			Handler:       _TwinPickService_PickStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SpotStream",
			Handler:       _TwinPickService_SpotStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/twinpick.proto",
}
