// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: api/proto/twinpick.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Duration définit les catégories de durée
type Duration int32

const (
	Duration_DURATION_LONG   Duration = 0 // pas de limite (défaut)
	Duration_DURATION_SHORT  Duration = 1 // <= 100 min
	Duration_DURATION_MEDIUM Duration = 2 // <= 120 min
)

// Enum value maps for Duration.
var (
	Duration_name = map[int32]string{
		0: "DURATION_LONG",
		1: "DURATION_SHORT",
		2: "DURATION_MEDIUM",
	}
	Duration_value = map[string]int32{
		"DURATION_LONG":   0,
		"DURATION_SHORT":  1,
		"DURATION_MEDIUM": 2,
	}
)

func (x Duration) Enum() *Duration {
	p := new(Duration)
	*p = x
	return p
}

func (x Duration) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Duration) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_twinpick_proto_enumTypes[0].Descriptor()
}

func (Duration) Type() protoreflect.EnumType {
	return &file_api_proto_twinpick_proto_enumTypes[0]
}

func (x Duration) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Duration.Descriptor instead.
func (Duration) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_twinpick_proto_rawDescGZIP(), []int{0}
}

// OrderFilter définit l'ordre de tri
type OrderFilter int32

const (
	OrderFilter_ORDER_POPULAR       OrderFilter = 0 // par popularité (défaut)
	OrderFilter_ORDER_HIGHEST_RATED OrderFilter = 1 // par note
	OrderFilter_ORDER_NEWEST        OrderFilter = 2 // par date
	OrderFilter_ORDER_SHORTEST      OrderFilter = 3 // par durée
)

// Enum value maps for OrderFilter.
var (
	OrderFilter_name = map[int32]string{
		0: "ORDER_POPULAR",
		1: "ORDER_HIGHEST_RATED",
		2: "ORDER_NEWEST",
		3: "ORDER_SHORTEST",
	}
	OrderFilter_value = map[string]int32{
		"ORDER_POPULAR":       0,
		"ORDER_HIGHEST_RATED": 1,
		"ORDER_NEWEST":        2,
		"ORDER_SHORTEST":      3,
	}
)

func (x OrderFilter) Enum() *OrderFilter {
	p := new(OrderFilter)
	*p = x
	return p
}

func (x OrderFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_twinpick_proto_enumTypes[1].Descriptor()
}

func (OrderFilter) Type() protoreflect.EnumType {
	return &file_api_proto_twinpick_proto_enumTypes[1]
}

func (x OrderFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderFilter.Descriptor instead.
func (OrderFilter) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_twinpick_proto_rawDescGZIP(), []int{1}
}

// Film représente un film avec ses métadonnées
type Film struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Duration      int32                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"` // durée en minutes
	Directors     []string               `protobuf:"bytes,3,rep,name=directors,proto3" json:"directors,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Film) Reset() {
	*x = Film{}
	mi := &file_api_proto_twinpick_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Film) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Film) ProtoMessage() {}

func (x *Film) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_twinpick_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Film.ProtoReflect.Descriptor instead.
func (*Film) Descriptor() ([]byte, []int) {
	return file_api_proto_twinpick_proto_rawDescGZIP(), []int{0}
}

func (x *Film) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Film) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Film) GetDirectors() []string {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *Film) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

// Filters contient les filtres de résultats
type Filters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`                              // nombre max de résultats (0 = pas de limite)
	Duration      Duration               `protobuf:"varint,2,opt,name=duration,proto3,enum=twinpick.Duration" json:"duration,omitempty"` // filtre par durée
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_api_proto_twinpick_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_twinpick_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_api_proto_twinpick_proto_rawDescGZIP(), []int{1}
}

func (x *Filters) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Filters) GetDuration() Duration {
	if x != nil {
		return x.Duration
	}
	return Duration_DURATION_LONG
}

// ScrapperFilters contient les filtres pour le scraping Letterboxd
type ScrapperFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []string               `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`                          // genres à filtrer
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`                      // plateforme de streaming (ex: "netflix-fr")
	Order         OrderFilter            `protobuf:"varint,3,opt,name=order,proto3,enum=twinpick.OrderFilter" json:"order,omitempty"` // ordre de tri
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapperFilters) Reset() {
	*x = ScrapperFilters{}
	mi := &file_api_proto_twinpick_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapperFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapperFilters) ProtoMessage() {}

func (x *ScrapperFilters) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_twinpick_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapperFilters.ProtoReflect.Descriptor instead.
func (*ScrapperFilters) Descriptor() ([]byte, []int) {
	return file_api_proto_twinpick_proto_rawDescGZIP(), []int{2}
}

func (x *ScrapperFilters) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *ScrapperFilters) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ScrapperFilters) GetOrder() OrderFilter {
	if x != nil {
		return x.Order
	}
	return OrderFilter_ORDER_POPULAR
}

// PickRequest est la requête pour trouver des films en commun
type PickRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Usernames       []string               `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`                                    // noms d'utilisateurs Letterboxd (requis)
	Filters         *Filters               `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`                                        // filtres optionnels
	ScrapperFilters *ScrapperFilters       `protobuf:"bytes,3,opt,name=scrapper_filters,json=scrapperFilters,proto3" json:"scrapper_filters,omitempty"` // filtres de scraping optionnels
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PickRequest) Reset() {
	*x = PickRequest{}
	mi := &file_api_proto_twinpick_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickRequest) ProtoMessage() {}

func (x *PickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_twinpick_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickRequest.ProtoReflect.Descriptor instead.
func (*PickRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_twinpick_proto_rawDescGZIP(), []int{3}
}

func (x *PickRequest) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

func (x *PickRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *PickRequest) GetScrapperFilters() *ScrapperFilters {
	if x != nil {
		return x.ScrapperFilters
	}
	return nil
}

// PickResponse est la réponse contenant les films en commun
type PickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Films         []*Film                `protobuf:"bytes,1,rep,name=films,proto3" json:"films,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // nombre total de films trouvés
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickResponse) Reset() {
	*x = PickResponse{}
	mi := &file_api_proto_twinpick_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickResponse) ProtoMessage() {}

func (x *PickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_twinpick_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickResponse.ProtoReflect.Descriptor instead.
func (*PickResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_twinpick_proto_rawDescGZIP(), []int{4}
}

func (x *PickResponse) GetFilms() []*Film {
	if x != nil {
		return x.Films
	}
	return nil
}

func (x *PickResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// SpotRequest est la requête pour obtenir des suggestions
type SpotRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Filters         *Filters               `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	ScrapperFilters *ScrapperFilters       `protobuf:"bytes,2,opt,name=scrapper_filters,json=scrapperFilters,proto3" json:"scrapper_filters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SpotRequest) Reset() {
	*x = SpotRequest{}
	mi := &file_api_proto_twinpick_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotRequest) ProtoMessage() {}

func (x *SpotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_twinpick_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotRequest.ProtoReflect.Descriptor instead.
func (*SpotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_twinpick_proto_rawDescGZIP(), []int{5}
}

func (x *SpotRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SpotRequest) GetScrapperFilters() *ScrapperFilters {
	if x != nil {
		return x.ScrapperFilters
	}
	return nil
}

// SpotResponse est la réponse contenant les suggestions
type SpotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Films         []*Film                `protobuf:"bytes,1,rep,name=films,proto3" json:"films,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpotResponse) Reset() {
	*x = SpotResponse{}
	mi := &file_api_proto_twinpick_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotResponse) ProtoMessage() {}

func (x *SpotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_twinpick_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotResponse.ProtoReflect.Descriptor instead.
func (*SpotResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_twinpick_proto_rawDescGZIP(), []int{6}
}

func (x *SpotResponse) GetFilms() []*Film {
	if x != nil {
		return x.Films
	}
	return nil
}

func (x *SpotResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_api_proto_twinpick_proto protoreflect.FileDescriptor

const file_api_proto_twinpick_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/twinpick.proto\x12\btwinpick\"j\n" +
	"\x04Film\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\x12\x1c\n" +
	"\tdirectors\x18\x03 \x03(\tR\tdirectors\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\"O\n" +
	"\aFilters\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12.\n" +
	"\bduration\x18\x02 \x01(\x0e2\x12.twinpick.DurationR\bduration\"r\n" +
	"\x0fScrapperFilters\x12\x16\n" +
	"\x06genres\x18\x01 \x03(\tR\x06genres\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12+\n" +
	"\x05order\x18\x03 \x01(\x0e2\x15.twinpick.OrderFilterR\x05order\"\x9e\x01\n" +
	"\vPickRequest\x12\x1c\n" +
	"\tusernames\x18\x01 \x03(\tR\tusernames\x12+\n" +
	"\afilters\x18\x02 \x01(\v2\x11.twinpick.FiltersR\afilters\x12D\n" +
	"\x10scrapper_filters\x18\x03 \x01(\v2\x19.twinpick.ScrapperFiltersR\x0fscrapperFilters\"U\n" +
	"\fPickResponse\x12$\n" +
	"\x05films\x18\x01 \x03(\v2\x0e.twinpick.FilmR\x05films\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x80\x01\n" +
	"\vSpotRequest\x12+\n" +
	"\afilters\x18\x01 \x01(\v2\x11.twinpick.FiltersR\afilters\x12D\n" +
	"\x10scrapper_filters\x18\x02 \x01(\v2\x19.twinpick.ScrapperFiltersR\x0fscrapperFilters\"U\n" +
	"\fSpotResponse\x12$\n" +
	"\x05films\x18\x01 \x03(\v2\x0e.twinpick.FilmR\x05films\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount*F\n" +
	"\bDuration\x12\x11\n" +
	"\rDURATION_LONG\x10\x00\x12\x12\n" +
	"\x0eDURATION_SHORT\x10\x01\x12\x13\n" +
	"\x0fDURATION_MEDIUM\x10\x02*_\n" +
	"\vOrderFilter\x12\x11\n" +
	"\rORDER_POPULAR\x10\x00\x12\x17\n" +
	"\x13ORDER_HIGHEST_RATED\x10\x01\x12\x10\n" +
	"\fORDER_NEWEST\x10\x02\x12\x12\n" +
	"\x0eORDER_SHORTEST\x10\x032\xed\x01\n" +
	"\x0fTwinPickService\x125\n" +
	"\x04Pick\x12\x15.twinpick.PickRequest\x1a\x16.twinpick.PickResponse\x125\n" +
	"\x04Spot\x12\x15.twinpick.SpotRequest\x1a\x16.twinpick.SpotResponse\x125\n" +
	"\n" +
	"PickStream\x12\x15.twinpick.PickRequest\x1a\x0e.twinpick.Film0\x01\x125\n" +
	"\n" +
	"SpotStream\x12\x15.twinpick.SpotRequest\x1a\x0e.twinpick.Film0\x01B&Z$github.com/abroudoux/twinpick/api/pbb\x06proto3"

var (
	file_api_proto_twinpick_proto_rawDescOnce sync.Once
	file_api_proto_twinpick_proto_rawDescData []byte
)

func file_api_proto_twinpick_proto_rawDescGZIP() []byte {
	file_api_proto_twinpick_proto_rawDescOnce.Do(func() {
		file_api_proto_twinpick_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_twinpick_proto_rawDesc), len(file_api_proto_twinpick_proto_rawDesc)))
	})
	return file_api_proto_twinpick_proto_rawDescData
}

var file_api_proto_twinpick_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_twinpick_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_twinpick_proto_goTypes = []any{
	(Duration)(0),           // 0: twinpick.Duration
	(OrderFilter)(0),        // 1: twinpick.OrderFilter
	(*Film)(nil),            // 2: twinpick.Film
	(*Filters)(nil),         // 3: twinpick.Filters
	(*ScrapperFilters)(nil), // 4: twinpick.ScrapperFilters
	(*PickRequest)(nil),     // 5: twinpick.PickRequest
	(*PickResponse)(nil),    // 6: twinpick.PickResponse
	(*SpotRequest)(nil),     // 7: twinpick.SpotRequest
	(*SpotResponse)(nil),    // 8: twinpick.SpotResponse
}
var file_api_proto_twinpick_proto_depIdxs = []int32{
	0,  // 0: twinpick.Filters.duration:type_name -> twinpick.Duration
	1,  // 1: twinpick.ScrapperFilters.order:type_name -> twinpick.OrderFilter
	3,  // 2: twinpick.PickRequest.filters:type_name -> twinpick.Filters
	4,  // 3: twinpick.PickRequest.scrapper_filters:type_name -> twinpick.ScrapperFilters
	2,  // 4: twinpick.PickResponse.films:type_name -> twinpick.Film
	3,  // 5: twinpick.SpotRequest.filters:type_name -> twinpick.Filters
	4,  // 6: twinpick.SpotRequest.scrapper_filters:type_name -> twinpick.ScrapperFilters
	2,  // 7: twinpick.SpotResponse.films:type_name -> twinpick.Film
	5,  // 8: twinpick.TwinPickService.Pick:input_type -> twinpick.PickRequest
	7,  // 9: twinpick.TwinPickService.Spot:input_type -> twinpick.SpotRequest
	5,  // 10: twinpick.TwinPickService.PickStream:input_type -> twinpick.PickRequest
	7,  // 11: twinpick.TwinPickService.SpotStream:input_type -> twinpick.SpotRequest
	6,  // 12: twinpick.TwinPickService.Pick:output_type -> twinpick.PickResponse
	8,  // 13: twinpick.TwinPickService.Spot:output_type -> twinpick.SpotResponse
	2,  // 14: twinpick.TwinPickService.PickStream:output_type -> twinpick.Film
	2,  // 15: twinpick.TwinPickService.SpotStream:output_type -> twinpick.Film
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_twinpick_proto_init() }
func file_api_proto_twinpick_proto_init() {
	if File_api_proto_twinpick_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_twinpick_proto_rawDesc), len(file_api_proto_twinpick_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_twinpick_proto_goTypes,
		DependencyIndexes: file_api_proto_twinpick_proto_depIdxs,
		EnumInfos:         file_api_proto_twinpick_proto_enumTypes,
		MessageInfos:      file_api_proto_twinpick_proto_msgTypes,
	}.Build()
	File_api_proto_twinpick_proto = out.File
	file_api_proto_twinpick_proto_goTypes = nil
	file_api_proto_twinpick_proto_depIdxs = nil
}
